.autorc, .circleci/config.yml, package.json, yarn.lock
=> Theoretically configures CI for publishing

package.json
(I do realize `Version` is irrelevant for these changes)
=> [CI] Requires build

.circleci/config.yml, package.json
=> Attempts to build before release

.circleci/config.yml
=> Attempts to connect to workspace

.circleci/config.yml, package.json
=> Removes redundant steps

.circleci/config.yml, .gitignore, package.json, scripts/build.js, tsconfig.json, yarn.lock
. 
<details>
<summary>📦 Published PR as canary version: <code>0.0.2--canary.6.44.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install @artsy/icons@0.0.2--canary.6.44.0
yarn add @artsy/icons@0.0.2--canary.6.44.0
```
</details>
=> chore(ci): Test icon publishing pipeline 

package.json
=> chore(publish): bump version to get on track

.circleci/config.yml, package.json
Adds our docs publishing pipeline, which points at icons.artsy.net
=> chore(docs): add docs publishing

.circleci/config.yml, .gitignore, docs/next.config.js
=> chore(docs): fix build

package.json
Just manually incrementing this so that I can use the new icons.
=> chore: manually bumps version

README.md
This adds a README with some detail
=> docs(readme): Add Docs 

docs/components/Item.tsx
Fixes the build path for icons
=> fix(docs): fix build path for docs

docs/package.json, docs/yarn.lock, scripts/write.js
Adds typing for native HTML props like `style` and `title`.
=> fix(types): adds complete type

src/ImageSet.svg
Used on article pages for image sets.
=> feat: adds image set icon

src/Pending.svg
=> feat: adds pending icon

src/ArrowDown.svg, src/ArrowUp.svg
I just wound up re-drawing these because the originals were misaligned.
=> feat: adds up and down arrows

src/Pending.svg
=> fix(pending): updates svg

package.json, src/Google.svg, svgo.config.js, svgo/removeAttrsIfSameFill.js, yarn.lock
This took a bit of doing, but: I wrote a custom SVGO plugin that wraps their `removeAttrs` plugin; and only applies it if all the fills are the same.
=> feat: supports full color icons; adds google

src/Amex.svg, src/Card.svg, src/Discover.svg, src/Mastercard.svg, src/Visa.svg
Wound up just re-drawing these.
=> feat: adds cc icons

package.json
styled-components warnings were showing up
=> fix(deps): fixes peerdep ref

src/UploadFile.svg
=> feat(upload-file): Add UploadFile icon

src/UploadFile.svg
=> fix(icons): fix csv and upload 6

scripts/writeNative.js
This PR is the icons side of artsy/palette#1433
This PR updates `blackk100` in the native icons to `mono100`
=> chore: update black100 to mono100

src/ArrowUpRight.svg
This PR resolves [MOPRAT-842]
This PR adds a new icon called ArrowUpRightIcon
[MOPRAT-842]: https://artsyproduct.atlassian.net/browse/MOPRAT-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(MOPRAT-842): Add ArrowUpRightIcon

src/ArrowLeft.svg
This PR resolves part of [MOPRAT-863]
This PR adds ArrowLeftIcon 
[MOPRAT-863]: https://artsyproduct.atlassian.net/browse/MOPRAT-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Add ArrowLeftIcon
